import {it,expect} from 'vitest';
import request from 'supertest';
import {randomUUID} from 'node:crypto';
import {app,signupTestOrg} from './helpers';
import {pool} from '../src/db/pool';
const a=(token:string)=>({Authorization:`Bearer ${token}`});
it('branch defaults are administrator-managed, company-bound, current and revoked without granting facility access',async()=>{
 const ca=await signupTestOrg(),other=await signupTestOrg();const branchId=randomUUID();
 const user=(await pool.query('SELECT id FROM users WHERE organization_id=$1',[ca.organizationId])).rows[0].id;
 const foreign=(await pool.query('SELECT id FROM users WHERE organization_id=$1',[other.organizationId])).rows[0].id;
 const body={name:'Synthetic California',default_state:'CA',default_territory:'QA West',is_active:true};
 expect((await request(app).put('/api/branches/'+branchId).set(a(ca.token)).send(body)).status).toBe(200);
 expect((await request(app).put('/api/branches/'+branchId).set(a(other.token)).send(body)).status).toBe(404);
 expect((await request(app).put('/api/branches/assignments/'+foreign).set(a(ca.token)).send({branch_id:branchId})).status).toBe(404);
 expect((await request(app).put('/api/branches/assignments/'+foreign).set(a(other.token)).send({branch_id:branchId})).status).toBe(404);
 expect((await request(app).put('/api/branches/assignments/'+user).set(a(ca.token)).send({branch_id:branchId})).status).toBe(200);
 const search=()=>request(app).get('/api/portfolio/facility-search').set(a(ca.token));
 expect((await search()).body).toMatchObject({preferences:{home_state:'CA',home_territory:'QA West'},facilities:[]});
 expect((await request(app).get('/api/portfolio/facility-search').set(a(other.token))).body.preferences).toEqual({home_state:null,home_territory:null});
 await request(app).put('/api/branches/'+branchId).set(a(ca.token)).send({...body,default_state:'FL',default_territory:'QA East'});
 expect((await search()).body.preferences.home_state).toBe('FL');
 await pool.query("UPDATE users SET role='technician' WHERE id=$1",[user]);
 expect((await request(app).put('/api/branches/assignments/'+user).set(a(ca.token)).send({branch_id:null})).status).toBe(403);
 expect((await search()).body.preferences.home_state).toBe('FL');
 await pool.query('UPDATE company_branches SET is_active=false WHERE id=$1',[branchId]);
 expect((await search()).body.preferences).toEqual({home_state:null,home_territory:null});
 await pool.query('UPDATE users SET is_active=false WHERE id=$1',[user]);
 expect((await search()).status).toBe(403);
});
