import {it,expect} from 'vitest';
import request from 'supertest';
import {randomUUID} from 'node:crypto';
import {app,signupTestOrg,createPortfolioHierarchy,createTestOpening} from './helpers';
import {pool} from '../src/db/pool';
const auth=(token:string)=>({Authorization:`Bearer ${token}`});
it('owner grants only named facilities; provider cannot redelegate; revocation denies direct reads, media and queued writes',async()=>{
 const owner=await signupTestOrg('Synthetic customer'),v=await signupTestOrg('Synthetic Vortex'),d=await signupTestOrg('Synthetic DH Pace');
 const f=await createPortfolioHierarchy(owner.token),second=await createPortfolioHierarchy(owner.token);
 const o=await createTestOpening(owner.token,f.buildingId);
 const url=`/api/provider-assignments/${f.propertyId}/${v.organizationId}`;
 expect((await request(app).put(url).set(auth(v.token)).send({active:true})).status).toBe(404);
 expect((await request(app).put(url).set(auth(owner.token)).send({active:true})).status).toBe(200);
 const search=await request(app).get('/api/portfolio/facility-search').set(auth(v.token));
 expect(search.body.facilities.map((x:any)=>x.id)).toEqual([f.propertyId]);
 expect((await request(app).get('/api/portfolio/facility-search').set(auth(d.token))).body.facilities).toEqual([]);
 expect((await request(app).get('/api/portfolio/facility-dashboard/'+second.propertyId).set(auth(v.token))).status).toBe(404);
 expect((await request(app).get('/api/openings/'+o.id).set(auth(v.token))).status).toBe(200);
 expect((await request(app).get('/api/openings/'+o.id).set(auth(d.token))).status).toBe(404);
 const photo=await pool.query("INSERT INTO photos(opening_id,storage_url) VALUES($1,'https://example.test/private') RETURNING id",[o.id]);
 await request(app).put(url).set(auth(owner.token)).send({active:false});
 expect((await request(app).get('/api/openings/'+o.id).set(auth(v.token))).status).toBe(404);
 expect((await request(app).get('/api/photos/'+photo.rows[0].id+'/access').set(auth(v.token))).status).toBe(404);
 expect((await request(app).post('/api/hardware').set(auth(v.token)).send({opening_id:o.id,component_type:'closer'})).status).toBe(403);
 const queued={schema_version:1,app_version:'test',protocol_version:1,operation_id:randomUUID(),device_id:randomUUID(),entity_id:randomUUID(),opening_id:o.id,base_server_revision:null,payload:{component_type:'closer',mounting_scope:'opening',condition:'worn',identity_status:'unresolved',review_state:'pending',replacement_required:true}};
 const denied=await request(app).post('/api/sync/components').set(auth(v.token)).send(queued);expect(denied.status).toBe(403);
 expect((await request(app).get('/api/portfolio/facility-search').set(auth(v.token))).body.facilities).toEqual([]);
});
it('purchasing requires owner-approved exact identity/document, excludes serviceable, blocks whole mixed review, and invalidates changed identity',async()=>{
 const owner=await signupTestOrg(),other=await signupTestOrg();const f=await createPortfolioHierarchy(owner.token);
 const o=await createTestOpening(owner.token,f.buildingId),unfinished=await createTestOpening(owner.token,f.buildingId);
 await request(app).put(`/api/openings/${o.id}/frame`).set(auth(owner.token)).send({material:'Steel',condition:'good'});
 await request(app).post(`/api/openings/${o.id}/door-leaves`).set(auth(owner.token)).send({leaf_role:'single',condition:'good'});
 const h=await request(app).post('/api/hardware').set(auth(owner.token)).send({opening_id:o.id,component_type:'closer',manufacturer:'SYNTHETIC',model_number:'QA',condition:'worn',identity_status:'established',review_state:'reviewed',replacement_required:true});
 const good=await request(app).post('/api/hardware').set(auth(owner.token)).send({opening_id:o.id,component_type:'hinge',condition:'good',review_state:'reviewed',replacement_required:true});
 expect((await request(app).post(`/api/openings/${o.id}/complete`).set(auth(owner.token))).status).toBe(200);
 const review=(ids=[o.id])=>request(app).post('/api/purchasing/review').set(auth(owner.token)).send({opening_ids:ids});
 expect((await review()).body).toMatchObject({blocked:true,items:[]});
 const approval={document_url:'https://example.test/synthetic-approved.pdf',document_sha256:'a'.repeat(64),provenance:'technician_selected',active:true};
 expect((await request(app).put('/api/purchasing/approvals/'+h.body.id).set(auth(other.token)).send(approval)).status).toBe(404);
 expect((await request(app).put('/api/purchasing/approvals/'+h.body.id).set(auth(owner.token)).send(approval)).status).toBe(200);
 const ready=await review();expect(ready.body.blocked).toBe(false);expect(ready.body.items).toHaveLength(1);expect(ready.body.items[0]).toMatchObject({component_id:h.body.id,document_url:approval.document_url,provenance:'technician_selected'});expect(ready.body.excluded[0].component_id).toBe(good.body.id);
 const mixed=await review([o.id,unfinished.id]);expect(mixed.body.blocked).toBe(true);expect(mixed.body.items).toEqual([]);
 await request(app).patch('/api/hardware/'+h.body.id).set(auth(owner.token)).send({model_number:'CHANGED'});
 expect((await review()).body.blocked).toBe(true);
 expect((await request(app).get(`/api/openings/${o.id}/purchasing-eligibility`).set(auth(owner.token))).body.blocked).toBe(true);
 await request(app).patch('/api/hardware/'+h.body.id).set(auth(owner.token)).send({condition:'good'});
 expect((await review()).body).toMatchObject({status:'no_replacements',items:[]});
 await pool.query("UPDATE users SET role='technician' WHERE organization_id=$1",[owner.organizationId]);
 expect((await request(app).put('/api/purchasing/approvals/'+h.body.id).set(auth(owner.token)).send(approval)).status).toBe(403);
});
