-- Development rollback only. Disabling RLS re-exposes tables to roles that
-- already have Data API privileges, so review grants before using this file.

ALTER TABLE organizations DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE portfolios DISABLE ROW LEVEL SECURITY;
ALTER TABLE properties DISABLE ROW LEVEL SECURITY;
ALTER TABLE buildings DISABLE ROW LEVEL SECURITY;
ALTER TABLE openings DISABLE ROW LEVEL SECURITY;
ALTER TABLE opening_frames DISABLE ROW LEVEL SECURITY;
ALTER TABLE door_leaves DISABLE ROW LEVEL SECURITY;
ALTER TABLE hardware_components DISABLE ROW LEVEL SECURITY;
ALTER TABLE service_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE inspection_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE photos DISABLE ROW LEVEL SECURITY;
ALTER TABLE health_score_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE work_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE maintenance_schedules DISABLE ROW LEVEL SECURITY;
